In [1]:
import pandas as pd
import numpy as np

In [2]:
games_df = pd.read_csv('data/games.csv')
games_df

Unnamed: 0  Season        Date  HID  AID  N  POFF        Open  \
0               0       1  1975-11-07   13   28  0     0  1975-11-06   
1               1       1  1975-11-07   20   12  0     0  1975-11-06   
2               2       1  1975-11-07   43    8  0     0  1975-11-06   
3               3       1  1975-11-07   33    4  0     0  1975-11-06   
4               4       1  1975-11-07   41   34  0     0  1975-11-06   
...           ...     ...         ...  ...  ... ..   ...         ...   
28985       28985      24  1999-06-15   41   17  0     1  1999-06-14   
28986       28986      24  1999-06-17   41   17  0     1  1999-06-16   
28987       28987      24  1999-06-20   41   17  0     1  1999-06-19   
28988       28988      24  1999-06-22   17   41  0     1  1999-06-21   
28989       28989      24  1999-06-24   17   41  0     1  1999-06-23   

          OddsH     OddsA  ...  HAST  AAST  HSTL  ASTL  HBLK  ABLK  HTOV  \
0      1.196537  4.833232  ...  26.0  26.0   7.0  14.0   5.0   4.0  25.0   
1      1.394620  2.957488  ...  14.0  21.0   7.0   5.0   5.0   2.0  22.0   
2      1.502570  2.536599  ...  29.0  26.0   9.0  15.0  10.0   3.0  23.0   
3      1.275743  3.778120  ...  36.0  27.0   9.0   7.0   7.0   4.0  13.0   
4      1.112895  7.379109  ...  31.0  18.0   5.0  10.0   6.0   6.0  18.0   
...         ...       ...  ...   ...   ...   ...   ...   ...   ...   ...   
28985  1.488863  2.580145  ...  20.0  13.0   4.0   2.0   2.0   7.0  10.0   
28986  1.559415  2.377968  ...  15.0  13.0  12.0   6.0   2.0   3.0  12.0   
28987  1.521256  2.480785  ...  21.0  12.0   8.0   9.0   7.0   1.0  17.0   
28988  1.496122  2.556796  ...  17.0  17.0  13.0   8.0   8.0   4.0  13.0   
28989  1.433385  2.783270  ...  11.0  18.0   7.0   6.0   3.0   7.0  11.0   

       ATOV   HPF   APF  
0      14.0  27.0  26.0  
1      21.0  31.0  33.0  
2      18.0  19.0  31.0  
3      17.0  18.0  22.0  
4      22.0  27.0  25.0  
...     ...   ...   ...  
28985   9.0  27.0  20.0  
28986  16.0  21.0  23.0  
28987  14.0  23.0  22.0  
28988  14.0  17.0  21.0  
28989  15.0  19.0  25.0  

[28990 rows x 42 columns]

In [3]:
games_df.groupby(['Season']).count()

Unnamed: 0  Date   HID   AID     N  POFF  Open  OddsH  OddsA     H  \
Season                                                                       
1             1014  1014  1014  1014  1014  1014  1014   1014   1014  1014   
2             1023  1023  1023  1023  1023  1023  1023   1023   1023  1023   
3             1087  1087  1087  1087  1087  1087  1087   1087   1087  1087   
4             1179  1179  1179  1179  1179  1179  1179   1179   1179  1179   
5             1175  1175  1175  1175  1175  1175  1175   1175   1175  1175   
6             1180  1180  1180  1180  1180  1180  1180   1180   1180  1180   
7             1183  1183  1183  1183  1183  1183  1183   1183   1183  1183   
8             1184  1184  1184  1184  1184  1184  1184   1184   1184  1184   
9             1180  1180  1180  1180  1180  1180  1180   1180   1180  1180   
10            1257  1257  1257  1257  1257  1257  1257   1257   1257  1257   
11            1261  1261  1261  1261  1261  1261  1261   1261   1261  1261   
12            1260  1260  1260  1260  1260  1260  1260   1260   1260  1260   
13             791   791   791   791   791   791   791    791    791   791   
14            1264  1264  1264  1264  1264  1264  1264   1264   1264  1264   
15            1260  1260  1260  1260  1260  1260  1260   1260   1260  1260   
16            1260  1260  1260  1260  1260  1260  1260   1260   1260  1260   
17            1277  1277  1277  1277  1277  1277  1277   1277   1277  1277   
18            1271  1271  1271  1271  1271  1271  1271   1271   1271  1271   
19            1314  1314  1314  1314  1314  1314  1314   1314   1314  1314   
20            1319  1319  1319  1319  1319  1319  1319   1319   1319  1319   
21            1309  1309  1309  1309  1309  1309  1309   1309   1309  1309   
22            1315  1315  1315  1315  1315  1315  1315   1315   1315  1315   
23            1315  1315  1315  1315  1315  1315  1315   1315   1315  1315   
24            1312  1312  1312  1312  1312  1312  1312   1312   1312  1312   

        ...  HAST  AAST  HSTL  ASTL  HBLK  ABLK  HTOV  ATOV   HPF   APF  
Season  ...                                                              
1       ...  1014  1014  1014  1014  1014  1014  1014  1014  1014  1014  
2       ...  1023  1023  1023  1023  1023  1023  1023  1023  1023  1023  
3       ...  1087  1087  1087  1087  1087  1087  1087  1087  1087  1087  
4       ...  1179  1179  1179  1179  1179  1179  1179  1179  1179  1179  
5       ...  1175  1175  1175  1175  1175  1175  1175  1175  1175  1175  
6       ...  1180  1180  1180  1180  1180  1180  1180  1180  1180  1180  
7       ...  1183  1183  1183  1183  1183  1183  1183  1183  1183  1183  
8       ...  1184  1184  1184  1184  1184  1184  1184  1184  1184  1184  
9       ...  1180  1180  1180  1180  1180  1180  1180  1180  1180  1180  
10      ...  1257  1257  1257  1257  1257  1257  1257  1257  1257  1257  
11      ...  1261  1261  1261  1261  1261  1261  1261  1261  1261  1261  
12      ...  1260  1260  1260  1260  1260  1260  1260  1260  1260  1260  
13      ...   791   791   791   791   791   791   791   791   791   791  
14      ...  1264  1264  1264  1264  1264  1264  1264  1264  1264  1264  
15      ...  1260  1260  1260  1260  1260  1260  1260  1260  1260  1260  
16      ...  1260  1260  1260  1260  1260  1260  1260  1260  1260  1260  
17      ...  1277  1277  1277  1277  1277  1277  1277  1277  1277  1277  
18      ...  1271  1271  1271  1271  1271  1271  1271  1271  1271  1271  
19      ...  1314  1314  1314  1314  1314  1314  1314  1314  1314  1314  
20      ...  1319  1319  1319  1319  1319  1319  1319  1319  1319  1319  
21      ...  1309  1309  1309  1309  1309  1309  1309  1309  1309  1309  
22      ...  1315  1315  1315  1315  1315  1315  1315  1315  1315  1315  
23      ...  1315  1315  1315  1315  1315  1315  1315  1315  1315  1315  
24      ...  1312  1312  1312  1312  1312  1312  1312  1312  1312  1312  

[24 rows x 41 columns]

In [4]:
team_ids = games_df['AID'].unique()
team_ids.sort()
team_ids

array([ 0,  1,  2,  3,  4,  5,  8, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21,
       22, 24, 25, 28, 30, 33, 34, 35, 39, 41, 42, 43, 44])

In [5]:
team_ids.shape

(30,)

In [6]:
games_df.memory_usage(index=True).sum() / (1024 ** 2)
# 10 MB

np.float64(9.28952407836914)

In [7]:
games_df.memory_usage(index=True, deep=True).sum() / (1024 ** 2)
# 13 MB

np.float64(12.109519958496094)

In [8]:
games_df[games_df['Season'].isin([1,2])].memory_usage(index=True, deep=True).sum() / (1024 ** 2)
# 1 MB

np.float64(0.8664150238037109)

In [9]:
games_df[games_df['Season'].isin([1,2])]

Unnamed: 0  Season        Date  HID  AID  N  POFF        Open     OddsH  \
0              0       1  1975-11-07   13   28  0     0  1975-11-06  1.196537   
1              1       1  1975-11-07   20   12  0     0  1975-11-06  1.394620   
2              2       1  1975-11-07   43    8  0     0  1975-11-06  1.502570   
3              3       1  1975-11-07   33    4  0     0  1975-11-06  1.275743   
4              4       1  1975-11-07   41   34  0     0  1975-11-06  1.112895   
...          ...     ...         ...  ...  ... ..   ...         ...       ...   
2032        2032       2  1977-06-19   15   17  0     1  1977-06-18  1.385194   
2033        2033       2  1977-06-21   15   17  0     1  1977-06-20  1.481056   
2034        2034       2  1977-06-23   15   17  0     1  1977-06-22  1.416219   
2035        2035       2  1977-06-26   17   15  0     1  1977-06-25  1.625010   
2036        2036       2  1977-06-28   17   15  0     1  1977-06-27  1.602546   

         OddsA  ...  HAST  AAST  HSTL  ASTL  HBLK  ABLK  HTOV  ATOV   HPF  \
0     4.833232  ...  26.0  26.0   7.0  14.0   5.0   4.0  25.0  14.0  27.0   
1     2.957488  ...  14.0  21.0   7.0   5.0   5.0   2.0  22.0  21.0  31.0   
2     2.536599  ...  29.0  26.0   9.0  15.0  10.0   3.0  23.0  18.0  19.0   
3     3.778120  ...  36.0  27.0   9.0   7.0   7.0   4.0  13.0  17.0  18.0   
4     7.379109  ...  31.0  18.0   5.0  10.0   6.0   6.0  18.0  22.0  27.0   
...        ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
2032  3.004898  ...  18.0  21.0   6.0   8.0   6.0   6.0  11.0  11.0  23.0   
2033  2.606012  ...  22.0  11.0   6.0   3.0   7.0   3.0  12.0  16.0  30.0   
2034  2.856591  ...  20.0  26.0   5.0   7.0   5.0   3.0  14.0  14.0  29.0   
2035  2.229593  ...  30.0  30.0   6.0  11.0   3.0   3.0  14.0  12.0  19.0   
2036  2.276896  ...  30.0  22.0   6.0  13.0   1.0   2.0  18.0  11.0  22.0   

       APF  
0     26.0  
1     33.0  
2     31.0  
3     22.0  
4     25.0  
...    ...  
2032  13.0  
2033  30.0  
2034  27.0  
2035  29.0  
2036  23.0  

[2037 rows x 42 columns]

In [10]:
games_df['Season'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [11]:
from xgboost import XGBClassifier
# read data
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
data = load_iris()
X_train, X_test, y_train, y_test = train_test_split(data['data'], data['target'], test_size=.2)
# create model instance
bst = XGBClassifier(n_estimators=2, max_depth=2, learning_rate=1, objective='binary:logistic')
# fit model
bst.fit(X_train, y_train)
# make predictions
preds = bst.predict(X_test)

In [12]:
preds

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 2, 2, 1, 2, 1, 0, 0, 2, 1, 1, 1, 1, 0,
       1, 2, 2, 0, 1, 0, 0, 1])

In [13]:
len(data['target'])

150

In [14]:
data['data']

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
games_df[games_df['Season'].isin([3])]

Unnamed: 0  Season        Date  HID  AID  N  POFF        Open     OddsH  \
2037        2037       3  1977-11-11   35   19  0     0  1977-11-10  2.487971   
2038        2038       3  1977-11-11   11   15  0     0  1977-11-10  1.791779   
2039        2039       3  1977-11-11   24   43  0     0  1977-11-10  1.215281   
2040        2040       3  1977-11-11   12    2  0     0  1977-11-10  1.368089   
2041        2041       3  1977-11-11   44   21  0     0  1977-11-10  3.133913   
...          ...     ...         ...  ...  ... ..   ...         ...       ...   
3119        3119       3  1978-06-09   11   15  0     1  1978-06-08  2.307073   
3120        3120       3  1978-06-13   15   17  0     1  1978-06-12  1.344306   
3121        3121       3  1978-06-15   15   17  0     1  1978-06-14  1.321660   
3122        3122       3  1978-06-18   17   15  0     1  1978-06-17  1.772285   
3123        3123       3  1978-06-20   17   15  0     1  1978-06-19  1.833714   

         OddsA  ...  HAST  AAST  HSTL  ASTL  HBLK  ABLK  HTOV  ATOV   HPF  \
2037  1.518776  ...  23.0  21.0   7.0   5.0   5.0   0.0  15.0  12.0  32.0   
2038  1.960023  ...  20.0  25.0  12.0   7.0  10.0   2.0  15.0  17.0  28.0   
2039  4.518083  ...  33.0  19.0  10.0   6.0   5.0   2.0  21.0  18.0  37.0   
2040  3.096829  ...  20.0  22.0   8.0  15.0   6.0   7.0  22.0  18.0  19.0   
2041  1.361593  ...  27.0  33.0   8.0  16.0   1.0   3.0  24.0  20.0  25.0   
...        ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
3119  1.589013  ...  21.0  24.0   5.0   6.0   5.0   1.0  13.0  12.0  27.0   
3120  3.239061  ...  26.0  21.0   2.0   9.0   5.0   2.0  13.0  12.0  28.0   
3121  3.393001  ...  21.0  21.0   3.0   3.0   9.0   3.0  10.0  14.0  31.0   
3122  1.985699  ...  27.0  29.0   7.0   8.0   5.0   3.0  14.0  13.0  24.0   
3123  1.908746  ...  23.0  21.0   3.0   3.0   6.0   4.0   7.0   9.0  30.0   

       APF  
2037  20.0  
2038  25.0  
2039  28.0  
2040  31.0  
2041  24.0  
...    ...  
3119  25.0  
3120  28.0  
3121  22.0  
3122  30.0  
3123  26.0  

[1087 rows x 42 columns]

In [16]:
games_df['Season'].iloc[-1]

np.int64(24)

In [17]:
games_df[games_df['Season'].isin([3])]['A']

2037    1
2038    1
2039    0
2040    1
2041    1
       ..
3119    1
3120    0
3121    0
3122    1
3123    1
Name: A, Length: 1087, dtype: int64

In [18]:
for row in games_df[games_df['Season'] == 3].index:
    print(row)

2037
2038
2039
2040
2041
2042
2043
2044
2045
2046
2047
2048
2049
2050
2051
2052
2053
2054
2055
2056
2057
2058
2059
2060
2061
2062
2063
2064
2065
2066
2067
2068
2069
2070
2071
2072
2073
2074
2075
2076
2077
2078
2079
2080
2081
2082
2083
2084
2085
2086
2087
2088
2089
2090
2091
2092
2093
2094
2095
2096
2097
2098
2099
2100
2101
2102
2103
2104
2105
2106
2107
2108
2109
2110
2111
2112
2113
2114
2115
2116
2117
2118
2119
2120
2121
2122
2123
2124
2125
2126
2127
2128
2129
2130
2131
2132
2133
2134
2135
2136
2137
2138
2139
2140
2141
2142
2143
2144
2145
2146
2147
2148
2149
2150
2151
2152
2153
2154
2155
2156
2157
2158
2159
2160
2161
2162
2163
2164
2165
2166
2167
2168
2169
2170
2171
2172
2173
2174
2175
2176
2177
2178
2179
2180
2181
2182
2183
2184
2185
2186
2187
2188
2189
2190
2191
2192
2193
2194
2195
2196
2197
2198
2199
2200
2201
2202
2203
2204
2205
2206
2207
2208
2209
2210
2211
2212
2213
2214
2215
2216
2217
2218
2219
2220
2221
2222
2223
2224
2225
2226
2227
2228
2229
2230
2231
2232
2233
2234
2235
2236


In [19]:
games_df.iloc[2]

Unnamed: 0             2
Season                 1
Date          1975-11-07
HID                   43
AID                    8
N                      0
POFF                   0
Open          1975-11-06
OddsH            1.50257
OddsA           2.536599
H                      1
A                      0
HSC                  127
ASC                  123
HFGM                49.0
AFGM                49.0
HFGA                92.0
AFGA                99.0
HFG3M                0.0
AFG3M                1.0
HFG3A                0.0
AFG3A                6.0
HFTM                29.0
AFTM                24.0
HFTA                36.0
AFTA                31.0
HORB                14.0
AORB                18.0
HDRB                36.0
ADRB                27.0
HRB                 50.0
ARB                 45.0
HAST                29.0
AAST                26.0
HSTL                 9.0
ASTL                15.0
HBLK                10.0
ABLK                 3.0
HTOV                23.0
ATOV                18.0


In [20]:
games_df[(games_df['HID'] == 22) & (games_df.index < 2037)]

Unnamed: 0  Season        Date  HID  AID  N  POFF        Open     OddsH  \
15            15       1  1975-11-08   22   41  0     0  1975-11-07  1.876048   
53            53       1  1975-11-15   22   15  0     0  1975-11-14  1.263272   
65            65       1  1975-11-18   22   28  0     0  1975-11-17  1.166394   
81            81       1  1975-11-21   22   18  0     0  1975-11-20  1.097287   
102          102       1  1975-11-25   22    8  0     0  1975-11-24  1.169742   
...          ...     ...         ...  ...  ... ..   ...         ...       ...   
1871        1871       2  1977-04-18   22   13  0     0  1977-04-17  1.349185   
1926        1926       2  1977-04-27   22   34  0     0  1977-04-26  1.673131   
1935        1935       2  1977-04-29   22   18  0     0  1977-04-28  1.616525   
1979        1979       2  1977-05-11   22   19  0     1  1977-05-10  1.853308   
1987        1987       2  1977-05-13   22   19  0     1  1977-05-12  1.771681   

         OddsA  ...  HAST  AAST  HSTL  ASTL  HBLK  ABLK  HTOV  ATOV   HPF  \
15    1.862782  ...  27.0  23.0  12.0   4.0   2.0   7.0  11.0  19.0  24.0   
53    3.904515  ...  25.0  18.0  12.0  10.0   2.0   4.0  15.0  25.0  22.0   
65    5.477127  ...  27.0  20.0   3.0   4.0   1.0   2.0  23.0  15.0  28.0   
81    8.285708  ...  26.0  20.0   8.0   3.0   4.0   7.0  12.0   9.0  30.0   
102   5.395175  ...  26.0  16.0  10.0   9.0   5.0   3.0  15.0  21.0  28.0   
...        ...  ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   
1871  3.208384  ...  21.0  21.0  10.0   7.0   3.0   2.0  14.0  19.0  26.0   
1926  2.138547  ...  46.0  31.0   9.0  10.0   6.0   7.0  12.0  16.0  17.0   
1935  2.247069  ...  38.0  31.0   7.0   4.0   4.0  10.0  13.0  15.0  23.0   
1979  1.886466  ...  26.0  29.0   6.0   7.0   4.0   9.0  11.0   9.0  19.0   
1987  1.986515  ...  25.0  24.0   9.0   5.0   5.0   7.0  11.0  19.0  24.0   

       APF  
15    20.0  
53    32.0  
65    32.0  
81    28.0  
102   22.0  
...    ...  
1871  24.0  
1926  19.0  
1935  25.0  
1979  31.0  
1987  26.0  

[90 rows x 42 columns]

In [21]:
games_df[games_df['Season'] == 3].shape[0]

1087

In [24]:
a = games_df['HID'].unique()
a.sort()
a

array([ 0,  1,  2,  3,  4,  5,  8, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21,
       22, 24, 25, 28, 30, 33, 34, 35, 39, 41, 42, 43, 44])

In [25]:
b = games_df['AID'].unique()
b.sort()
b

array([ 0,  1,  2,  3,  4,  5,  8, 11, 12, 13, 15, 16, 17, 18, 19, 20, 21,
       22, 24, 25, 28, 30, 33, 34, 35, 39, 41, 42, 43, 44])

In [59]:
for i, row in enumerate(games_df.iterrows()):
    match = row[1]
    # print(match)
    print(match['A'])
    print(type(match['A']))
    break
    

0
<class 'int'>


In [66]:
curr_season = 4 - 1
last_2_seasons = [curr_season - 1, curr_season - 2]
games_2_last_season = games_df[games_df['Season'].isin(last_2_seasons)]

all_teams_hid = games_2_last_season['HID'].unique()
all_teams_aid = games_2_last_season['AID'].unique()
all_teams_hid.sort()
all_teams_aid.sort()
print(all_teams_hid,)
print(len(all_teams_aid))

[ 1  2  4  8 11 12 13 15 17 18 19 20 21 22 24 25 28 33 34 35 41 42 43]
23


In [53]:
len(games_df.loc[games_df['HID'] == 2])

Unnamed: 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

In [54]:
count = ((games_df['HID'] == 2) & (games_df['H'] == 1)).sum()
print(count)

689


In [55]:
count = len(games_df.loc[(games_df['HID'] == 2) & (games_df['H'] == 1)])
print(count)

689


In [56]:
games_df.shape[0]

28990

In [57]:
type(games_df.shape[0])

int

In [60]:
games_df.loc[games_df['HID'] == 22, 'HSC'].sum()

np.int64(102944)

In [64]:
games_df.loc[games_df['HID'] == 22, 'HSC'].tolist()

[111,
 103,
 102,
 106,
 111,
 122,
 131,
 95,
 116,
 93,
 103,
 104,
 120,
 110,
 99,
 104,
 124,
 92,
 91,
 113,
 122,
 100,
 109,
 120,
 106,
 116,
 128,
 120,
 110,
 123,
 118,
 111,
 123,
 102,
 135,
 104,
 112,
 121,
 107,
 128,
 124,
 107,
 122,
 102,
 126,
 137,
 121,
 119,
 115,
 112,
 120,
 101,
 112,
 104,
 85,
 125,
 99,
 87,
 122,
 102,
 93,
 97,
 98,
 107,
 105,
 106,
 111,
 97,
 111,
 112,
 93,
 115,
 119,
 120,
 117,
 119,
 132,
 117,
 108,
 101,
 111,
 103,
 125,
 110,
 105,
 102,
 132,
 118,
 123,
 105,
 94,
 114,
 108,
 96,
 124,
 103,
 119,
 96,
 109,
 95,
 93,
 125,
 113,
 120,
 113,
 110,
 107,
 123,
 120,
 118,
 117,
 115,
 132,
 106,
 116,
 121,
 105,
 121,
 121,
 102,
 100,
 117,
 98,
 113,
 121,
 102,
 99,
 113,
 125,
 92,
 110,
 117,
 106,
 90,
 94,
 106,
 155,
 96,
 108,
 132,
 118,
 97,
 107,
 106,
 96,
 86,
 112,
 103,
 109,
 118,
 126,
 94,
 134,
 103,
 127,
 109,
 129,
 102,
 101,
 127,
 88,
 110,
 109,
 105,
 105,
 100,
 96,
 96,
 96,
 133,
 121,
 110,
